CREATE TABLE Citizen (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    SURNAME VARCHAR(50) NOT NULL,
    DOB DATE NOT NULL,
    SSN VARCHAR(15) NOT NULL,
    PHONE VARCHAR(8) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STREET VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);